server: 
    port: 8081

spring:
    data:
        mongodb:
            host: mongodb.localhost
            port: 27017
            database: PlayApp

logging:
  level:
     root: DEBUG
     com.playapp.starter.dataloading: DEBUG
     com.playapp.starter.controller: WARN

playyo: 
    app:
        jwtSecret: someSecret
        jwtExpirationMs: 86400000

    